sudo: required
language: php
dist: trusty

addons:
  chrome: stable

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - touch ./database/test.sqlite

script:
  - php artisan serve &

  - php artisan migrate --seed --env=testing
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    - quentyaiden@gmail.com